# Upload everything to staging
stages:
  - test
  - deploy

deploy to data.trezor.io:
  stage: deploy
  needs: []
  variables:
    GIT_STRATEGY: clone
  only:
    refs:
      - master
  when: manual
  before_script: []
  script:
    - source ${DEPLOY_DATA_KEYFILE}
    - nix-shell --run "./ci/s3sync.sh"
  tags:
    - deploy
